// Zurc — home: composição editorial em eixos, com dados compartilhados e seções reutilizáveis.
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { projects } from "../data/projects";
import { processSteps } from "../data/site";
import { services } from "../data/services";

const ProjectPreview = ({ project }: { project: typeof projects[number] }) => <Link href={`/projetos/${project.slug}`} className="project-card"><div className="project-image"><img src={project.image} alt={`Visual conceitual do projeto ${project.title}`} loading="lazy" /></div><div className="project-card-meta"><span>{project.label}</span><ArrowUpRight size={16} /></div><h3>{project.title}</h3><p>{project.category}</p></Link>;

export default function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-index">[ 00 — INTRO ]</div><div className="hero-copy"><div className="eyebrow"><i /> ZURC AGENCY / DIGITAL STUDIO</div><h1>Tecnologia<br /><em>sem ruído.</em></h1><p>Sites, automações e soluções em IA construídas para resolver problemas reais.</p><div className="hero-actions"><Link className="button button-red" href="/contato">Falar com a Zurc <ArrowUpRight size={16} /></Link><a className="text-link" href="#servicos">Conhecer serviços <ArrowDownRight size={16} /></a></div></div><div className="hero-mark" aria-hidden="true"><span /><span /><b /></div><div className="hero-footer"><span>WEB / AUTOMAÇÃO / IA / SOB MEDIDA</span><span>SCROLL PARA EXPLORAR ↓</span></div></div></section>
  <section id="servicos" className="section section-services"><div className="container"><div className="section-heading split"><div><div className="eyebrow"><i /> 01 / SERVIÇOS</div><h2>O que fazemos<br /><em>com clareza.</em></h2></div><p>Do primeiro diagnóstico à última linha de código, cada entrega parte de uma pergunta objetiva: o que precisa ficar mais simples?</p></div><div className="service-list">{services.map((service) => <Link href={`/servicos#${service.slug}`} className="service-row" key={service.id}><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.shortDescription}</p><ArrowUpRight size={18} /></Link>)}</div></div></section>
  <section id="processo" className="section section-process"><div className="container"><div className="eyebrow"><i /> 02 / ABORDAGEM</div><div className="process-heading"><h2>Do problema<br /><em>à solução.</em></h2><p>Sem atalhos performáticos. Um processo que organiza o pensamento antes de acelerar a execução.</p></div><div className="process-grid">{processSteps.map((step) => <article key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></div></section>
  <section id="projetos" className="section section-projects"><div className="container"><div className="section-heading split"><div><div className="eyebrow"><i /> 03 / SELECIONADOS</div><h2>Projetos<br /><em>em construção.</em></h2></div><p>Estudos conceituais em interface, automação e sistemas digitais. Nenhum resultado inventado: só hipóteses bem desenhadas.</p></div><div className="project-grid">{projects.map((project) => <ProjectPreview key={project.id} project={project} />)}</div><Link className="text-link all-projects" href="/projetos">Ver todos os projetos <ArrowUpRight size={16} /></Link></div></section>
  <section id="sobre" className="section section-about"><div className="container about-grid"><div><div className="eyebrow"><i /> 04 / SOBRE A ZURC</div><h2>Pensamos antes<br /><em>de construir.</em></h2></div><div className="about-copy"><p>A Zurc une design, desenvolvimento, automação e inteligência artificial para criar soluções digitais claras, precisas e feitas para resolver problemas reais.</p><Link className="text-link" href="/sobre">Conhecer a Zurc <ArrowUpRight size={16} /></Link></div><div className="about-stamp" aria-hidden="true">Z<br /><span>↓</span></div></div></section>
  <section className="final-cta"><div className="container"><div className="eyebrow"><i /> 05 / PRÓXIMO PASSO</div><h2>Tem um problema que<br /><em>a tecnologia resolve?</em></h2><p>Descreva o problema. A gente organiza o próximo passo.</p><Link className="button button-red" href="/contato">Falar com a Zurc <ArrowUpRight size={16} /></Link></div></section>
</>; }
